intel/e2eAIOK

Dockerfile-ubuntu18.04/DockerfilePytorch

Testing dlrm data processing and found java is missing in docker

[Dockerfile]install java other wise spark won't able to run

---

e2eAIOK/SDA/modeladvisor/DIENAdvisor.py
modelzoo/dien/README.md

[DIEN] update on distributed training and env variable setting in README

---

modelzoo/WnD/TensorFlow2/README.md
modelzoo/WnD/TensorFlow2/wnd.patch
modelzoo/dien/README.md
modelzoo/dien/run_dien_all_in_one.sh

upgrade spark version from 3.0 to 3.2, refine readme.

[WnD] upgrade spark version

---

e2eAIOK/SDA/modeladvisor/DIENAdvisor.py
modelzoo/dien/README.md
modelzoo/dien/meta.yaml
modelzoo/dien/train/dien.patch

Add below config so we don't need to enter tensorflow conda

---

README.md

Update name to Intel® End-to-End AI Optimization Kit

---

modelzoo/dien/feature_engineering/preprocessing.py
modelzoo/dien/feature_engineering/split_for_distribute.sh

DIEN add auto split script and fix args bug

---

.github/workflows/e2eaiok_nightly_pypi.yml
.github/workflows/e2eaiok_release_pypi.yml

update action after adding token

---

modelzoo/dien/feature_engineering/preprocessing.py
modelzoo/dlrm/data_processing/preprocessing.py
scripts/config_proxy
scripts/run_docker
scripts/run_docker_l
scripts/start_e2eaiok_docker.py

1. add TF210 docker support in start_e2eaiok_docker script
2. fixed python version issue in dien and dlrm data processing script

[V0.2.1] docker upgrade fix

---

conf/e2eaiok_defaults_bert_example.conf
demo/builtin/bert/BERT_DEMO.ipynb
modelzoo/bert/README.md

This PR is updated with some word fixes for the BERT.
Please help review this PR. Thx. @Jian-Zhang

[v0.2] Some small word fix for the bert

---

scripts/start_e2eaiok_docker.py

related issue: https://github.com/intel/e2eAIOK/issues/81

Update start_e2eaiok_docker to use dockerhub

---

Dockerfile-ubuntu18.04/DockerfilePytorch110
Dockerfile-ubuntu18.04/DockerfileTensorflow
docs/source/quickstart.rst
modelzoo/dien/run_dien_all_in_one.sh
modelzoo/resnet/run_all_in_one.sh
modelzoo/resnet/run_inference.sh
modelzoo/resnet/run_train.sh
tests/cicd/docker_horovod_test.sh
tests/cicd/jenkins_bert_test.sh
tests/cicd/jenkins_bert_test_dist.sh
tests/cicd/jenkins_denas_asr.sh
tests/cicd/jenkins_denas_bert.sh
tests/cicd/jenkins_denas_cnn.sh
tests/cicd/jenkins_denas_vit.sh
tests/cicd/jenkins_dien_test.sh
tests/cicd/jenkins_pipeline_test.sh
tests/cicd/jenkins_resnet_test.sh
tests/cicd/jenkins_resnet_test_dist.sh
tests/cicd/jenkins_wnd_test.sh
tests/cicd/jenkins_wnd_test_dist.sh
tests/cicd/test_denas.bats

1. minor fix about cicd scripts, passed cicd for v0.1/v0.2 workloads and denas tests
2. refine Dockerfiles
3. refine docs

[v0.3] code refine, pass cicd

---

conf/denas/nlp/e2eaiok_denas_train_bert.conf
e2eAIOK/DeNas/module/nlp/Linear_super.py
e2eAIOK/DeNas/module/nlp/bert_attention_super.py
e2eAIOK/DeNas/module/nlp/bert_embedding_super.py
e2eAIOK/DeNas/module/nlp/bert_encoder_super.py
e2eAIOK/DeNas/module/nlp/bert_intermediate_super.py
e2eAIOK/DeNas/module/nlp/bert_pooler_super.py
e2eAIOK/DeNas/module/nlp/layernorm_super.py
e2eAIOK/DeNas/nlp/bert_trainer.py
e2eAIOK/DeNas/nlp/supernet_bert.py
e2eAIOK/DeNas/nlp/utils.py
e2eAIOK/DeNas/nlp/utils_eval.py
e2eAIOK/DeNas/search/BaseSearchEngine.py
e2eAIOK/common/trainer/data/data_builder_squad.py

This PR is updated with the followings:
- Updating the latency calculation part in the DENAS BERT search process.
- Fix the errors when using distributed training.
which is tested well in the local env:

[v0.3 DENAS] Fix the search process issues in the BERT

---

e2eAIOK/DeNas/README.md

[v0.3] DE-NAS readme update

---

e2eAIOK/DeNas/search/SigoptSearchEngine.py
e2eAIOK/DeNas/train.py

sigopt search for VIT and ASR returns latest cdds and best structure, this PR is to fix this bug to return correct best structure.

[v1.0 DENAS] return correct best structure for sigopt search

---

.github/workflows/e2eaiok_release_pypi.yml
.github/workflows/integration_test_denas_asr.yml
.github/workflows/integration_test_denas_cnn.yml
.github/workflows/integration_test_denas_nlp.yml
.github/workflows/integration_test_denas_vit.yml
.github/workflows/integration_test_workload_bert.yml
.github/workflows/integration_test_workload_dien.yml
.github/workflows/integration_test_workload_dlrm.yml
.github/workflows/integration_test_workload_pipeline.yml
.github/workflows/integration_test_workload_resnet.yml
.github/workflows/integration_test_workload_rnnt.yml
.github/workflows/integration_test_workload_wnd.yml
.github/workflows/unittest.yml
Dockerfile-ubuntu18.04/DockerfilePytorch112
dev/release_default_linux.sh
e2eAIOK/DeNas/asr/trainer/__init__.py
tests/cicd/DeNasJenkinsfile
tests/cicd/jenkins_denas_asr.sh
tests/cicd/jenkins_denas_bert.sh
tests/cicd/jenkins_denas_cnn.sh
tests/cicd/jenkins_denas_vit.sh

1. Add GitHub Workflow CI auto-tests, aligned with [BigDL style](https://github.com/intel-analytics/BigDL/tree/main/.github/workflows)
2. Add CI for DeNas trainer

[v1.0] add self-hosted ci workflow and add ci for denas train

---

.github/workflows/integration_test_denas_asr.yml
.github/workflows/integration_test_denas_cnn.yml
.github/workflows/integration_test_denas_nlp.yml
.github/workflows/integration_test_denas_vit.yml
.github/workflows/integration_test_workload_bert.yml
.github/workflows/integration_test_workload_dien.yml
.github/workflows/integration_test_workload_dlrm.yml
.github/workflows/integration_test_workload_pipeline.yml
.github/workflows/integration_test_workload_resnet.yml
.github/workflows/integration_test_workload_rnnt.yml
.github/workflows/integration_test_workload_wnd.yml
docs/source/_modules/hydroai.hydroDB.rst
docs/source/_modules/hydroai.hydroautolearner.rst
docs/source/_modules/hydroai.hydroconfig.rst
docs/source/_modules/hydroai.hydroconnector.rst
docs/source/_modules/hydroai.hydromodel.rst
docs/source/_modules/hydroai.hydromodelzoo.rst
docs/source/_modules/hydroai.hydroserver.rst
docs/source/_modules/hydroai.hydroweblistener.rst
docs/source/_modules/hydroai.rst
docs/source/_modules/modules.rst
docs/source/_modules/run_e2eaiok.rst
docs/source/advanced.rst
docs/source/codingstyle.rst
docs/source/documentingstyle.rst
docs/source/quickstart.rst
e2eAIOK/SDA/modeladvisor/RNNTAdvisor.py
modelzoo/minigo/README.md
scripts/performance_test_guide.md
setup.py

Found some files still containing words: hydroai or aidk.
Fix renaming typos (hydroai, aidk --> aiok).

[v1.0] fix typos

---

conf/denas/cv/e2eaiok_denas_cnn.conf
conf/denas/cv/e2eaiok_denas_vit.conf
e2eAIOK/DeNas/cv/supernet_transformer.py
e2eAIOK/DeNas/module/cv/Linear_super.py
e2eAIOK/DeNas/module/cv/__init__.py
e2eAIOK/DeNas/module/cv/layernorm_super.py
e2eAIOK/DeNas/module/cv/multihead_super.py
e2eAIOK/DeNas/run_train.sh
tests/unittest/test_denas_cv_trainer.py

Add unittest for CV trainer(CNN and VIT). Local test works well

[v1.0]ADD unittest for CV trainer(CNN&VIT)

---

conf/denas/cv/e2eaiok_denas_train_cnn.conf
e2eAIOK/DeNas/cv/cv_trainer.py
e2eAIOK/DeNas/run_train.sh
e2eAIOK/common/trainer/torch_trainer.py

[v1.0]refine CNN trainer hyperparameters

---

e2eAIOK/DeNas/cv/cv_trainer.py
tests/unittest/test_denas_cv_trainer.py

@xuechendi @zigzagcai  Refined current CV(CNN&VIT) trainer with output. Local test works well. And github action uts also passed.

[v1.0]refine CV(CNN&VIT) unittests

---

README.md

Update README with Denas links

---

e2eAIOK/DeNas/asr/asr_trainer.py
e2eAIOK/DeNas/run_train.sh
e2eAIOK/DeNas/train.py

return mean wer after evaluation to prevent different wer from different ranks

[v1.0 DENAS] ASR WER allreduce for dist training

---

conf/denas/asr/e2eaiok_denas_asr.conf
conf/denas/cv/e2eaiok_denas_vit.conf
conf/denas/nlp/e2eaiok_denas_bert.conf
e2eAIOK/DeNas/search/EvolutionarySearchEngine.py
e2eAIOK/DeNas/search/MOSigoptSearchEngine.py
e2eAIOK/DeNas/search/SigoptSearchEngine.py

1. Make SigoptSearchEngine load obsearvation_budget from conf file
2. Minor fix about EA

[v1.0] Refine DeNas SigoptSearchEngine

---

conf/denas/asr/e2eaiok_denas_asr.conf
conf/denas/cv/e2eaiok_denas_cnn.conf
conf/denas/cv/e2eaiok_denas_vit.conf
conf/denas/nlp/e2eaiok_denas_bert.conf
e2eAIOK/DeNas/search/EvolutionarySearchEngine.py
tests/unittest/test_denas_evolutionary.py

1. Move one DeNas EA parameter(scale_factor=10) from hard-coded to config file

[v1.0] Refine DeNas EA

---

README.md

[v1.0] update performance explaination content

---

modelzoo/rnnt/pytorch/rnnt.patch

* add gradient clipping to fix loss NAN issue
*  move layer normalization to config option

[v1.1 RNN-T] rnnt full dataset optimization

---

Dockerfile-ubuntu18.04/DockerfilePytorch112
e2eAIOK/ModelAdapter/engine_core/adapter/adversarial/cdan_adapter.py
e2eAIOK/ModelAdapter/training/task.py
tests/unittest/test_ma_adapter.py

- fix the glibc version bug
- fix the input args name mismatch bug

[v1.1] Model adaptor bug fix

---

setup.py

Remove chendi's email in setup.py

---

setup.py

setup.py change author

---

e2eAIOK/DeNas/asr/data/processing/features.py
e2eAIOK/DeNas/asr/model_builder_denas_asr.py
tests/unittest/test_denas_asr_model_builder.py

* add `load_pretrained_model` for DE-NAS ASR to load pre-trained model
* add support of DE-NAS ASR to load pre-trained model
* for integration test with Pruner
* this patch test will be triggered in UT & CI/CD

[v1.1 DE-NAS ASR] [ISSUE-184] DE-NAS ASR load pre-trained model

---

e2eAIOK/ModelAdapter/engine_core/distiller/utils/manager.py
tests/unittest/test_ma_distiller.py

- Due to code security scan, add close file to after read files in save logits function 
- Add save logits function check in UT

[v1.1][ISSUE-188] Refine Distiller close file and UT

---

Dockerfile-ubuntu18.04/DockerfilePytorch
Dockerfile-ubuntu18.04/DockerfilePytorch110
Dockerfile-ubuntu18.04/DockerfilePytorch112
Dockerfile-ubuntu18.04/DockerfileTensorflow

Dockerfile
Refine Dockerfile to optimize PyPI metrics
UT and Integration Test

[v1.1] Refine Dockerfile

---

.github/workflows/e2eaiok_ma_nightly_pypi.yml
.github/workflows/e2eaiok_ma_release_pypi.yml

Add PyPI Continous Delivery for Model Adapter
Enhance Continous Delivery
Unit Test

[v1.1] add model adapter pypi publish

---

Dockerfile-ubuntu18.04/DockerfilePytorch112
tests/cicd/jenkins_ma_adapter_test.sh
tests/cicd/jenkins_ma_baseline_ddp_test.sh
tests/cicd/jenkins_ma_distiller_test.sh
tests/cicd/jenkins_ma_finetuner_test.sh

Update the oneapi version.
To support performance test.
Existing ci/cd workflow.

[WIP][v1.1][ISSUE-209] update oneapi version

---

Dockerfile-ubuntu18.04/DockerfilePytorch
Dockerfile-ubuntu18.04/DockerfilePytorch110
Dockerfile-ubuntu18.04/DockerfilePytorch112
Dockerfile-ubuntu18.04/DockerfileTensorflow

Remove docker unused libs
Remove docker unused libs
UT

[v1.1] remove docker unused libs

---

e2eAIOK/SDA/README.md

fix incorrect links in SDA README.md
fix incorrect links in SDA README.md
UT

[v1.1] fix SDA README.md

---

demo/builtin/dlrm/DLRM_DEMO.ipynb

update DLRM notebook with pip install guide
provide pip install option in notebook
not tested

[v1.1][ISSUE-218]Update DLRM notebook with pip installation code block

---

.github/workflows/integration_test_workload_rnnt.yml
.travis.yml
Dockerfile-ubuntu18.04/DockerfilePytorch112
Dockerfile-ubuntu18.04/README.md
README.md
demo/builtin/rnnt/RNNT_DEMO.ipynb
modelzoo/rnnt/README.md
scripts/start_e2eaiok_docker.py
tests/cicd/Jenkinsfile
tests/cicd/JenkinsfileDistributed
tests/cicd/README.md

minor fix in PyTorch1.10 and PyTorch1.12 combining
minor fix in PyTorch1.10 and PyTorch1.12 combining
UT

[v1.1] minor fix about PyTorch1.10 and PyTorch1.12 combining

---

Dockerfile-ubuntu/README.md

Refine README in Dockerfile-ubuntu
Refine README in Dockerfile-ubuntu
UT

[v1.1] Refine README in Dockerfile-ubuntu

---

Dockerfile-ubuntu/DockerfilePytorch
Dockerfile-ubuntu/DockerfileTensorflow
Dockerfile-ubuntu/README.md
tests/cicd/src/test_categorify.py

Add jupyter service for DockerfilePytorch and DockerfileTensorflow
Add jupyter service for DockerfilePytorch and DockerfileTensorflow
UT

[v1.1] Add jupyter service for DockerfilePytorch and DockerfileTensorflow

---

demo/builtin/bert/BERT_DEMO.ipynb
demo/denas/bert/DENAS_BERT_DEMO.ipynb
demo/denas/hf/DENAS_HF_DEMO.ipynb

This PR is used for updating the usage info in the demo to notify the users how to get started.
To notify users how to get started (etc., data preparation or pre-trained model preparation).
These PR changes are covered by current SDA and DE-NAS CI/CD tests.

[v1.1][ISSUE-224] Added the Note to Info the Demo Usage

---

demo/builtin/rnnt/RNNT_DEMO.ipynb
demo/builtin/rnnt/workflow_prepare_rnnt.sh
demo/builtin/wnd/WND_DEMO.ipynb
demo/builtin/wnd/workflow_prepare_wnd.sh
demo/denas/asr/DENAS_ASR_DEMO.ipynb

Add workflow prepare scripts for WnD and RNN-T, add notes to clarify pre-requiements of demo
Add scripts to prepare SDA model. Clarify the pre-requirements to run demo (data preparation)
This PR is covered by current CI/CD test.

[v1.1][ISSUE-251] add workflow prepare script and demo notes

---

demo/builtin/dlrm/DLRM_DEMO.ipynb

update notes in dlrm demo
give notes to user
no tests needed

[v1.1][ISSUE-218]update notes on dlrm demo

---

demo/builtin/minigo/MiniGo_DEMO.ipynb
demo/builtin/minigo/workflow_prepare_minigo.sh
demo/builtin/resnet/RESNET_DEMO.ipynb
demo/builtin/resnet/workflow_prepare_resnet.sh

add workflow prepare scripts and demo notes for resnet and minigo
add workflow prepare scripts and demo notes for resnet and minigo
UT

[v1.1] add workflow prepare scripts and demo notes for resnet and minigo

---

demo/builtin/bert/workflow_prepare_bert.sh
demo/denas/bert/workflow_prepare_denas_bert.sh
demo/denas/hf/workflow_prepare_denas_hf.sh

This PR updated the workflow_prepare script for builtin-bert, denas-bert and denas-hf demos.
Added scripts to prepare SDA-BERT, DE-NAS BERT/HF model.
This unitest of this PR was covered by SDA/DE-NAS CI/CD.

[v1.1][ISSUE-224] Add the bulitin-bert/denas-bert/denas-hg Workflow Prepare Script

---

demo/builtin/dien/workflow_prepare_dien.sh
demo/builtin/dlrm/workflow_prepare_dlrm.sh

add new script to prepare workflow
make api simpler
no tests required

[v1.1][ISSUE-218]Add workflow prepare script

---

e2eAIOK/SDA/README.md
e2eAIOK/SDA/modeladvisor/BaseModelAdvisor.py
e2eAIOK/SDA/modeladvisor/RegisteredAdvisor.py

change argument name
be make the config name more explainable
using existing SDA UT

[v1.1][ISSUE-254]update config for sda

---

conf/ma/cicd/baseline/cifar100_res18.yaml
conf/ma/cicd/distiller/cifar100_kd_res50_res18.yaml
conf/ma/cicd/finetuner/cifar100_res50PretrainI21k.yaml
e2eAIOK/ModelAdapter/engine_core/distiller/utils/manager.py
e2eAIOK/ModelAdapter/main.py

Fix four code security scan problems
-  OS Access Violation - fixed by use hard code path
-  Uncontrolled Format String- fixed by use hard code path
-  Path Traversal - fixed by converge args to dict
-  Improper Resource Shutdown or Release - fixed by open file in __init() and close in __del()

[v1.1][ISSUE-263]Fix code security scan for Model Adapter

---

demo/ma/domain_adapter/Model_Adapter_Domain_Adapter_Walkthrough_Unet_KITS19.ipynb
demo/ma/domain_adapter/Model_Adapter_Domain_Adapter_builtin_Unet_KITS19.ipynb
demo/ma/domain_adapter/workflow_prepare_ma_da.sh

refine script to prepare workflow better
Make demo easy to use for users
No tests needed

[v1.1][ISSUE-257]Update workflow scripts on MA Domain Adapter demo

---

demo/builtin/dien/DIEN_DEMO.ipynb
demo/builtin/dien/workflow_prepare_dien.sh

update dien and dlrm demo workflow_prepare script
unify workflow_prepare method
tested in demo, paste evidence in PR

[v1.1][ISSUE-218]update dien demo workflow_prepare script

---

Dockerfile-ubuntu/DockerfilePytorch

[v1.1] fix DLRM

---

demo/builtin/dlrm/DLRM_DEMO.ipynb
demo/builtin/dlrm/workflow_prepare_dlrm.sh
e2eAIOK/SDA/modeladvisor/DLRMAdvisor.py

* update dlrm demo
* update SDA dlrm advisor with customize script path
* update dlrm patch to fix infer fail issue
use unified workflow_prepare.sh
existing CI/CD
manual notebook run

[v1.1][ISSUE-218] DLRM demo update with fixes on infer error

---

.github/workflows/e2eaiok_ma_nightly_pypi.yml
.github/workflows/e2eaiok_ma_release_pypi.yml
.github/workflows/setup_template/setup.py
e2eAIOK/ModelAdapter/requirements.txt

Fixing packaging of Model Adapter. Before it is blocked by a unofficial third-party library.
For relase of Model Adapter to pypi.
Current packaging test.

[v1.1][ISSUE-280] Fix Model Adapter packaging

---

.github/workflows/integration_test_workload_dlrm.yml
.github/workflows/integration_test_workload_minigo.yml
.github/workflows/integration_test_workload_wnd.yml
.github/workflows/unittest.yml
tests/cicd/conf/e2eaiok_defaults_minigo_example.conf
tests/cicd/jenkins_minigo_test.sh

change CI servers to self-hosted
change CI servers to self-hosted
UT

[v1.1] Refine CICD

---

demo/ma/distiller/Model_Adapter_Distiller_Walkthrough_VIT_to_ResNet18_CIFAR100.ipynb
demo/ma/distiller/Model_Adapter_Distiller_Walkthrough_VIT_to_ResNet18_CIFAR100_train_with_logits.ipynb
demo/ma/distiller/Model_Adapter_Distiller_Walkthrough_VIT_to_ResNet18_on_CIFAR100_save_logits.ipynb
demo/ma/distiller/Model_Adapter_Distiller_builtin_VIT_to_ResNet18_CIFAR100.ipynb
demo/ma/finetuner/Model_Adapter_Finetuner_Walkthrough_ResNet50_CIFAR100.ipynb
demo/ma/finetuner/Model_Adapter_Finetuner_builtin_ResNet50_CIFAR100.ipynb

- remove "recommend" in option
- Add notes for training acc for distiller
- remote duplicate "data" folder creating in Finetuner

[v1.1][ISSUE-274]Update Finetuner and Distiller demo

---

demo/builtin/dien/DIEN_DEMO.ipynb
demo/builtin/dlrm/DLRM_DEMO.ipynb

update notes to explain result AUC and format Deploy title

[v1.1][ISSUE-218]update demo text and format

---

README.md

Add next steps when installation complete
To clarify the next steps after pip install
UT

[v1.1] refine README.md

---

README.md

Final update for v1.1 documents

[v1.1][ISSUE-274]update Readme

---

Dockerfile-ubuntu/DockerfilePytorch
Dockerfile-ubuntu/DockerfilePytorch112
Dockerfile-ubuntu/DockerfileTensorflow

SDLe tasks required
SDLe tasks required
UT

[v1.1] fix Dockerfile

---

README.md

update model adaptor blog into readme
no need to test

update ma blog

---

RecDP/pyrecdp/autofe/AutoFE.py
RecDP/pyrecdp/primitives/profilers/type_infer.py
RecDP/pyrecdp/primitives/tabutils/__init__.py
RecDP/pyrecdp/primitives/tabutils/data_preprocess.py
RecDP/pyrecdp/primitives/tabutils/feature_normal_transform.py
RecDP/pyrecdp/primitives/tabutils/utils.py
RecDP/setup.py

Add __init__.py to tabutils and fix some bugs
To make Covid19 use case runnable
Test by autofe covid19 use case

[v1.2][ISSUE-302]Fix tabutils and add init to make it pluggable to recdp

---

.github/workflows/unittest_autofe.yml
.github/workflows/unittest_feature_profiler_pandas.yml
.github/workflows/unittest_feature_profiler_spark.yml
.github/workflows/unittest_feature_wrangler_pandas.yml
.github/workflows/unittest_feature_wrangler_spark.yml
.github/workflows/unittest_recdp_individal_method_test.yml
.github/workflows/unittest_relational_builder_pandas.yml
.github/workflows/unittest_relational_builder_spark.yml
RecDP/README.md
RecDP/pyrecdp/autofe/AutoFE.py
RecDP/pyrecdp/autofe/BasePipeline.py
RecDP/pyrecdp/autofe/FeatureEstimator.py
RecDP/pyrecdp/autofe/FeatureProfiler.py
RecDP/pyrecdp/core/utils.py
RecDP/pyrecdp/primitives/profilers/statics.py

Fix issue for non-target-label dataset
To support customer segmentation dataset
UT

[v1.2][ISSUE-302]Fix issue for non-target-label dataset

---

RecDP/pyrecdp/autofe/FeatureEstimator.py
RecDP/pyrecdp/primitives/tabutils/__init__.py
RecDP/pyrecdp/primitives/tabutils/segmentation.py

add segment tabutils function
support segment tabutils
UT

[v1.2][ISSUE-302]add segment tabutils function

---

RecDP/pyrecdp/primitives/llmutils/near_dedup.py
RecDP/pyrecdp/primitives/llmutils/utils.py

fix small import issue
other wise spark run will lack of dependency
UT

[v1.2][ISSUE-3.6]Fix near_dedup import

---

RecDP/pyrecdp/primitives/llmutils/__init__.py
RecDP/pyrecdp/primitives/llmutils/shrink_jsonl.py
RecDP/tests/cicd/bashrun_unittest_llmutils.sh
RecDP/tests/test_llmutils.py

Change name typo
Fix name typo
UT

[v1.2][ISSUE-306]Fix typo for shrink

---

RecDP/pyrecdp/primitives/spark_data_processor/utils.py

Fix ray init incorrect parameters

[v1.2][ISSUE-306]Fix ray init

---

RecDP/pyrecdp/primitives/spark_data_processor/data_processor.py
RecDP/pyrecdp/primitives/spark_data_processor/start-spark-standalone.sh
RecDP/pyrecdp/primitives/spark_data_processor/utils.py

[v1.2][ISSUE-306]Add spark standalone script

---

RecDP/pyrecdp/primitives/llmutils/__init__.py
RecDP/pyrecdp/primitives/llmutils/classify.py
RecDP/pyrecdp/primitives/llmutils/decontaminate.py
RecDP/pyrecdp/primitives/llmutils/filter.py
RecDP/pyrecdp/primitives/llmutils/language_identify.py
RecDP/pyrecdp/primitives/llmutils/ppi_remove.py
RecDP/pyrecdp/primitives/spark_data_processor/data_processor.py
RecDP/pyrecdp/primitives/spark_data_processor/start-spark-standalone.sh
RecDP/pyrecdp/primitives/spark_data_processor/utils.py

Add other LLM functions holder

[v1.2][ISSUE-306]LLM utils place holder

---

RecDP/pyrecdp/primitives/llmutils/__init__.py
RecDP/pyrecdp/primitives/llmutils/language_identify.py
RecDP/setup.py
RecDP/tests/test_llmutils.py

support LLM language identify utils
support new capability
UT

[v1.2][ISSUE-306]LLM language identify

---

RecDP/pyrecdp/primitives/llmutils/__init__.py
RecDP/pyrecdp/primitives/llmutils/filter.py
RecDP/tests/cicd/bashrun_unittest_llmutils.sh
RecDP/tests/test_llmutils.py

Support basic URL filter
Support basic URL filtering mentioned in [The RefinedWeb dataset for Falcon LLM](https://arxiv.org/pdf/2306.01116.pdf)
UT

[v1.2][ISSUE-306]Added basic implementation to support URL filter.

---

RecDP/tests/cicd/bashrun_unittest_llmutils.sh

add ut trigger
some of the UT is missing in UT bashrun
UT

[v1.2][ISSUE-306]update bashrun to trigger test

---

RecDP/pyrecdp/primitives/llmutils/__init__.py
RecDP/pyrecdp/primitives/llmutils/near_dedup.py
RecDP/pyrecdp/primitives/llmutils/third_party/generate_connected_components.py
RecDP/pyrecdp/primitives/llmutils/third_party/generate_duplicates_dict.py
RecDP/pyrecdp/primitives/llmutils/utils.py
RecDP/tests/cicd/bashrun_unittest_llmutils.sh
RecDP/tests/test_llmutils.py

provide near_dedup spark interface version
per EasyData request
UT

[v1.2][ISSUE-306]Add near_dedup_spark interface

---

RecDP/pyrecdp/primitives/llmutils/utils.py
RecDP/tests/test_llmutils.py

fast fix for last PR to make sure added global_id is always at first oridinal

[v1.2][ISSUE-306]another fixing

---

RecDP/pyrecdp/primitives/llmutils/pii_remove.py
RecDP/tests/test_llmutils.py

Change to use embbed way spark
Easydata integration
UT

[v1.2][ISSUE-306]  run pii remove with pyspark support

---

RecDP/pyrecdp/primitives/llmutils/__init__.py
RecDP/pyrecdp/primitives/llmutils/global_dedup.py
RecDP/pyrecdp/primitives/llmutils/global_hash.py
RecDP/pyrecdp/primitives/llmutils/index_based_reduction.py
RecDP/pyrecdp/primitives/llmutils/near_dedup.py
RecDP/pyrecdp/primitives/llmutils/utils.py
RecDP/tests/cicd/bashrun_unittest_llmutils.sh
RecDP/tests/test_llmutils.py

support global deduplication function for decontamination.
new feature
UT

[v1.2][ISSUE-306]Global dedup

---

RecDP/pyrecdp/primitives/llmutils/pii/pii_redaction.py
RecDP/pyrecdp/primitives/llmutils/pii_remove.py
RecDP/tests/cicd/bashrun_unittest_llmutils.sh
RecDP/tests/data/llm_data/pii_test.jsonl
RecDP/tests/test_llmutils.py

Refine code to make it easier to check if PII has been modified.
Easydata integration
UT

[v1.2][ISSUE-306] Refine code to make it easier to check if PII has been modified.

---

RecDP/pyrecdp/primitives/llmutils/README.md

[v1.2][ISSUE-306]LLM readme

---

RecDP/pyrecdp/primitives/llmutils/__init__.py
RecDP/pyrecdp/primitives/llmutils/convert.py
RecDP/pyrecdp/primitives/llmutils/text_normalization.py
RecDP/pyrecdp/primitives/llmutils/utils.py
RecDP/tests/test_llmutils.py

support text normalization and doc conversion to parquet
llm components
UT

[v1.2][ISSUE-306]Text normaliztaion

---

RecDP/pyrecdp/primitives/llmutils/README.md

[v1.2][ISSUE-306]refine readme with notebook links

---

RecDP/examples/notebooks/llmutils/classify.ipynb
RecDP/examples/notebooks/llmutils/convert.ipynb
RecDP/examples/notebooks/llmutils/data_diversity_control.ipynb
RecDP/examples/notebooks/llmutils/decontamination.ipynb
RecDP/examples/notebooks/llmutils/document_split.ipynb
RecDP/examples/notebooks/llmutils/filter.ipynb
RecDP/examples/notebooks/llmutils/fuzzy_deduplication.ipynb
RecDP/examples/notebooks/llmutils/language_identify.ipynb
RecDP/examples/notebooks/llmutils/pii_removal.ipynb
RecDP/examples/notebooks/llmutils/prompt_enhancement.ipynb
RecDP/examples/notebooks/llmutils/text_fixer.ipynb
RecDP/examples/notebooks/llmutils/text_normalization.ipynb
RecDP/examples/notebooks/llmutils/text_quality_assessment.ipynb
RecDP/examples/notebooks/llmutils/toxicity_bias_control.ipynb
RecDP/pyrecdp/primitives/llmutils/README.md

Add demo notebooks place holder

[v1.2][ISSUE-306]Add notebook explanation

---

RecDP/examples/notebooks/llmutils/classify.ipynb
RecDP/examples/notebooks/llmutils/language_identify.ipynb

A demo notebook is provided to allow users to use the llm data processing tool in a friendly manner.
Friden
Notebook

Add notebook for language identify and classify operators

---

RecDP/MANIFEST.in
RecDP/examples/notebooks/llmutils/filter.ipynb
RecDP/examples/notebooks/llmutils/text_fixer.ipynb
RecDP/setup.py

Add Text Fixer and Filter notebook.
Demonstration 
Run notebook on colab

[v1.2][ISSUE-306]Add Text Fixer and Filter notebook.

---

RecDP/pyrecdp/core/cache_utils.py
RecDP/pyrecdp/core/model_utils.py

Add model download utilities
Reuse code to download model 
N/A

[v1.2][ISSUE-306] Add model download utility

---

RecDP/examples/notebooks/llmutils/classify.ipynb
RecDP/examples/notebooks/llmutils/language_identify.ipynb
RecDP/examples/notebooks/llmutils/text_quality_assessment.ipynb

Add notebook for quality classifier.
To help user better use this tool
Through demo

[v1.2][ISSUE-306] Add notebook for quality classifier

---

RecDP/examples/notebooks/llmutils/data_diversity_control.ipynb
RecDP/pyrecdp/primitives/llmutils/__init__.py
RecDP/pyrecdp/primitives/llmutils/diversity_analysis.py
RecDP/setup.py
RecDP/tests/cicd/bashrun_unittest_llmutils.sh
RecDP/tests/test_llmutils.py

Add diversity analysis function. 
support the new capability
UT

[v1.2][ISSUE-306]Add diversity analysis.

---

e2eAIOK/deltatuner/README.md
e2eAIOK/deltatuner/deltatuner/scores/utils.py

- refine the attn-layer structure-name mapping for de-score calculation on more models
- refine the readme to list the deltatuner validated models
To prove the deltatuner's compatible with multiple models
deltatuner unit-test has covered this PR's change

[v1.2][ISSUE-358] Validate the deltatuner denas-lora support for multiple causal language model

---

.github/workflows/integration_test_deltatuner.yml
.github/workflows/unittest_denas.yml
.github/workflows/unittest_ma.yml
.github/workflows/unittest_util.yml
example/instruction_tuning_pipeline/finetune_clm.py
tests/deltatuner/cicd/run_denas_lora.sh
tests/deltatuner/cicd/run_denas_ssf.sh
tests/deltatuner/cicd/run_lora.sh
tests/deltatuner/cicd/run_ssf.sh

[v1.2][ISSUE-356] Enable Deltatuner CI/CD

---

.github/workflows/unittest_llmutils_pipeline.yml
RecDP/pyrecdp/primitives/operations/__init__.py
RecDP/pyrecdp/primitives/operations/text_diversityindicate.py
RecDP/pyrecdp/primitives/operations/text_qualityscorer.py
RecDP/tests/test_llmutils_operations.py

add qualityscorer and diversity indicator to pipeline
UT

[v1.2][ISSUE-306]Refactor operations 4

---

tests/unittest/ma/test_ma_distiller.py
tests/unittest/ma/test_ma_transferrable_model.py

remove resnet18 downloading for ma unit test to avoid network issue

[v1.2][ISSUE-351]remove resnet18 downloading for ma unit test

---

RecDP/examples/notebooks/llmutils/document_split.ipynb
RecDP/examples/notebooks/llmutils/pii_removal.ipynb

Add notebook for sentence split and PII removal
UT

[v1.2][ISSUE-306] Add notebook for sentence split and PII removal

---

RecDP/pyrecdp/primitives/llmutils/filter.py
RecDP/pyrecdp/primitives/llmutils/profanity_filter.py
RecDP/pyrecdp/primitives/llmutils/text_fixer.py
RecDP/pyrecdp/primitives/operations/text_filter.py
RecDP/pyrecdp/primitives/operations/text_fixer.py
RecDP/tests/test_llmutils_operations.py

Refactor filter and text fixer.
UT

[v1.2][ISSUE-306]Refactor filter and text fixer.

---

RecDP/pyrecdp/primitives/llmutils/filter.py
RecDP/pyrecdp/primitives/llmutils/profanity_filter.py
RecDP/pyrecdp/primitives/llmutils/text_fixer.py

fix import error by moving resumable pipeline to function

---

RecDP/pyrecdp/primitives/llmutils/pii/detect/name_password_detection.py
RecDP/pyrecdp/primitives/llmutils/pii/detect/utils.py
RecDP/pyrecdp/primitives/llmutils/pii/pii_detection.py
RecDP/pyrecdp/primitives/llmutils/pii_remove.py
RecDP/pyrecdp/primitives/operations/text_pii_remove.py
RecDP/tests/test_llmutils.py

PII Remove based on the removal type specified by the user.
UT

[v1.2][ISSUE-306] PII Remove support remove entity types specified by the user.

---

RecDP/pyrecdp/primitives/llmutils/__init__.py
RecDP/pyrecdp/primitives/llmutils/diversity_analysis.py
RecDP/pyrecdp/primitives/operations/text_diversityindicate.py
RecDP/tests/test_llmutils.py

Support diversity analysis on ray.
UT

[v1.2][ISSUE-306] Support diversity analysis on ray.

---

RecDP/pyrecdp/LLM/TextPipeline.py
RecDP/pyrecdp/primitives/operations/base.py
RecDP/pyrecdp/primitives/operations/logging_utils.py
RecDP/pyrecdp/primitives/operations/text_filter.py
RecDP/setup.py

Support logger and statistics in operation.
Add new capability about logging.
UT

Support logger and statistics in operation.

---

RecDP/pyrecdp/LLM/TextPipeline.py
RecDP/pyrecdp/primitives/operations/base.py

Add statistics_flag for user to choose in TextPipeline.
Avoid decrease in execution speed because statistics.
UT

[v1.2][ISSUE-306]Add statistics_flag for user to choose in TextPipeline.

---

RecDP/pyrecdp/primitives/operations/text_language_identify.py

Add threshold for LanguageIdentify operators to filter data.

[v1.2][ISSUE-306]Support threshold filter for language identify operator.

---

RecDP/pyrecdp/primitives/llmutils/pii/detect/utils.py
RecDP/pyrecdp/primitives/llmutils/pii/pii_detection.py
RecDP/pyrecdp/primitives/llmutils/pii_remove.py
RecDP/pyrecdp/primitives/operations/text_pii_remove.py

Turn off ner detection to improve performance 
UT

[v1.2][ISSUE-306]  Turn off ner detection to improve performance

---

RecDP/pyrecdp/core/utils.py
RecDP/pyrecdp/primitives/llmutils/filter.py
RecDP/pyrecdp/primitives/operations/filter/__init__.py
RecDP/pyrecdp/primitives/operations/filter/alphanumeric_filter.py
RecDP/pyrecdp/primitives/operations/filter/average_line_length_filter.py
RecDP/pyrecdp/primitives/operations/filter/constant.py
RecDP/pyrecdp/primitives/operations/filter/maximum_line_length_filter.py
RecDP/pyrecdp/primitives/operations/filter/special_characters_filter.py
RecDP/pyrecdp/primitives/operations/filter/token_num_filter.py
RecDP/pyrecdp/primitives/operations/filter/word_num_filter.py
RecDP/setup.py
RecDP/tests/test_llmutils_operations.py

Support more filters.
To downsize llm finetune dataset.
UT

[v1.2][ISSUE-306]Support more filters.

---

RecDP/pyrecdp/primitives/llmutils/diversity_analysis.py
RecDP/pyrecdp/primitives/operations/text_diversityindicate.py

Enhanced the ability of diversity analysis to process full text.
UT

[v1.2][ISSUE-306]Enhanced the ability of diversity analysis to process full text.

---

RecDP/examples/notebooks/llmutils/toxicity_bias_control.ipynb
RecDP/pyrecdp/primitives/llmutils/__init__.py
RecDP/pyrecdp/primitives/llmutils/toxicity_score.py
RecDP/pyrecdp/primitives/operations/__init__.py
RecDP/pyrecdp/primitives/operations/text_toxicity.py
RecDP/setup.py
RecDP/tests/test_llmutils.py

Support to give the toxicity score for each doc.
To filter more doc with toxicity content.

[v1.2][ISSUE-306] Support toxicity score

---

RecDP/pyrecdp/primitives/llmutils/document/extractor.py
RecDP/pyrecdp/primitives/llmutils/document/reader.py
RecDP/pyrecdp/primitives/llmutils/document_extractor.py
RecDP/setup.py

…ead of statically in setup.py
Install the required libraries for document extract dynamically, instead of statically setup.py.
UT

[v1.2][ISSUE-306] Install the required libraries for document extract dynamically, instead of statically with setup.py.

---

RecDP/pyrecdp/primitives/llmutils/document/extractor.py
RecDP/pyrecdp/primitives/llmutils/document/reader.py
RecDP/pyrecdp/primitives/llmutils/document_extractor.py
RecDP/setup.py

Reverts intel/e2eAIOK#396
See conflicts to remaining two PR, reverts this one and merge the latest PR instead.
@chaojun-zhang , next time, please don't submit PR incrementally.

Revert "[v1.2][ISSUE-306] Install the required libraries for document extract dynamically, instead of statically with setup.py."

---

RecDP/pyrecdp/primitives/llmutils/document/extractor.py
RecDP/pyrecdp/primitives/llmutils/document/reader.py
RecDP/pyrecdp/primitives/llmutils/document/writer.py
RecDP/pyrecdp/primitives/llmutils/document_extractor.py
RecDP/setup.py
RecDP/tests/test_llmutils.py

Extract document to a single text by default
UT

[v1.2][ISSUE-306] Extract document to a single text by default

---

RecDP/pyrecdp/primitives/llmutils/utils.py
RecDP/tests/cicd/bashrun_unittest_llmutils.sh

bashrun_unittest_llmutils.sh UT failing is not reporting errors
UT

[v1.2][ISSUE-306]Update bashrun_unittest_llmutils.sh

---

.github/workflows/e2eaiok_deltatuner_nightly_pypi.yml

[v1.2][ISSUE-402] publish deltatuner to pypi

---

RecDP/pyrecdp/primitives/llmutils/classify.py
RecDP/pyrecdp/primitives/llmutils/language_identify.py
RecDP/pyrecdp/primitives/llmutils/quality_classifier.py
RecDP/pyrecdp/primitives/llmutils/toxicity_score.py
RecDP/pyrecdp/primitives/operations/text_language_identify.py
RecDP/pyrecdp/primitives/operations/text_qualityscorer.py
RecDP/pyrecdp/primitives/operations/text_toxicity.py

[v1.2][ISSUE-306] Add parameters explanation for quality_score, toxicify_score, language_idenfity ops.

---

.github/workflows/release_docker_e2eaiokv12.yml
Dockerfile-ubuntu/Dockerfile-v1.2

Add a v1.2 docker release action
SDLe-247 require a docker scan for vulnerabilities

[v1.2][ISSUE-416]Add one action to release v1.2

---

RecDP/pyrecdp/LLM/TextPipeline.py
RecDP/pyrecdp/primitives/operations/text_deduplication.py
RecDP/tests/test_llmutils_pipelines.py

Fix bugs when both fuzzy and global deduplication are added to pipeline
Bug fixing
UT

[v1.2][ISSUE-306]update text pipeline for fixing

---

RecDP/pyrecdp/primitives/llmutils/rouge_score_dedup.py
RecDP/pyrecdp/primitives/operations/__init__.py
RecDP/pyrecdp/primitives/operations/text_rouge_score_dedup.py
RecDP/setup.py
RecDP/tests/test_llmutils_operations.py

Support rouge_score deduplicate
UT

[v1.2][ISSUE-306] Support rouge_score deduplicate.

---

RecDP/pyrecdp/core/pipeline.py
RecDP/pyrecdp/primitives/operations/text_reader.py
RecDP/tests/data/llm_data/pipeline/pipeline_example.yaml
RecDP/tests/test_llmutils_pipelines.py

llm text pipeline support to load from YAML file
UT

[v1.2][ISSUE-306]  llm text pipeline support to load from YAML file

---

RecDP/pyrecdp/LLM/TextPipeline.py
RecDP/pyrecdp/primitives/operations/base.py
RecDP/pyrecdp/primitives/operations/text_deduplication.py
RecDP/pyrecdp/primitives/operations/text_reader.py
RecDP/tests/test_llmutils_pipelines.py

1. fix deduplication performance issue of redundant join
2. add statistic for deduplication
UT

[v1.2][ISSUE-306]add log and fix performance for deduplication

---

RecDP/pyrecdp/LLM/TextPipeline.py
RecDP/tests/test_llmutils_pipelines.py

Support Pandas DataFrame as input to launch pipeline
UT covered

[v1.2][ISSUE-306]Support pandas dataframe as input for execute and add UT

---

RecDP/pyrecdp/primitives/llmutils/perplexity_score.py
RecDP/pyrecdp/primitives/operations/__init__.py
RecDP/pyrecdp/primitives/operations/text_perplexity_score.py
RecDP/pyrecdp/primitives/operations/text_rouge_score_dedup.py
RecDP/tests/test_llmutils_operations.py

Support to generate perplexity_score and suport to store rouge score column
UT

[v1.2][ISSUE-306] Support to generate perplexity_score and suport to store rouge score column

---

RecDP/pyrecdp/primitives/llmutils/rouge_score_dedup.py
RecDP/pyrecdp/primitives/operations/__init__.py
RecDP/pyrecdp/primitives/operations/text_compare_dedup.py
RecDP/pyrecdp/primitives/operations/text_rouge_score_dedup.py

Refactor rouge_score_dedup to support more compute functions.
UT

[v1.2][ISSUE-306]Refactor rouge_score_dedup to support more compute functions

---

RecDP/pyrecdp/LLM/TextPipeline.py

Support to define engine_name for pipeline.

Support to define engine for pipeline

---

RecDP/pyrecdp/LLM/README.md
RecDP/pyrecdp/primitives/llmutils/qa_generate.py
RecDP/pyrecdp/primitives/llmutils/text_to_qa.py
RecDP/pyrecdp/primitives/operations/__init__.py
RecDP/pyrecdp/primitives/operations/text_to_qa.py

Add TextToQA operator which can generate QA dataset from given massive text
1. support for existing public LLM 
2. support OpenAI (todo)
3. support prompt generating for massive text (todo)

[v1.2][ISSUE-454][WIP] Add TextToQA operator

---

RecDP/examples/notebooks/llmutils/rag.ipynb
RecDP/pyrecdp/core/import_utils.py
RecDP/pyrecdp/primitives/llmutils/document/reader.py
RecDP/pyrecdp/primitives/operations/__init__.py
RecDP/pyrecdp/primitives/operations/doc_loader.py
RecDP/pyrecdp/primitives/operations/text_perplexity_score.py
RecDP/pyrecdp/primitives/operations/text_split.py
RecDP/tests/test_llmutils_operations.py
RecDP/tests/test_llmutils_pipelines.py

[v1.2][ISSUE-306] Bug fix and HTML  loader integration
UT

[v1.2][ISSUE-306] Add ParagraphsTextSplitter

---

RecDP/pyrecdp/LLM/README.md
RecDP/pyrecdp/core/model_utils.py
RecDP/pyrecdp/primitives/operations/__init__.py
RecDP/pyrecdp/primitives/operations/constant.py
RecDP/pyrecdp/primitives/operations/filter/special_characters_filter.py
RecDP/pyrecdp/primitives/operations/filter/token_num_filter.py
RecDP/pyrecdp/primitives/operations/filter/word_num_filter.py
RecDP/pyrecdp/primitives/operations/filter/word_repetition_filter.py
RecDP/pyrecdp/primitives/operations/text_sentence_resplit.py
RecDP/pyrecdp/primitives/operations/text_unicode_fixer.py
RecDP/pyrecdp/primitives/operations/text_whitespace_normalization.py
RecDP/tests/test_llmutils_operations.py

Fix LLM readme to show rag pipeline example.
No code change

[v1.2][ISSUE-306] Fix LLM readme to show rag pipeline example.

---

RecDP/pyrecdp/primitives/operations/constant.py
RecDP/pyrecdp/primitives/operations/doc_loader.py
RecDP/tests/test_llmutils_operations.py

.
Support urlloader to crawl web pages.
support new feature
UT

[v1.2][ISSUE-306]Support urlloader to crawl web pages.

---

RecDP/pyrecdp/primitives/operations/text_ingestion.py

Change Haystack Elasticsearch to support multi nodes.
improve performance and multi node support
existing UT

[v1.2] [ISSUE-488] Create document store handler inside partition function to support the multi actors/task of multi nodes

---

RecDP/pyrecdp/primitives/operations/doc_loader.py

.
Fix a URLLoader bug.
If URLLoader can't request any response,  fetch_data_and_sub_links will return wrong result.
UT

[v1.2][ISSUE-306]Fix a URLLoader bug.

---

RecDP/examples/notebooks/llmutils/contraction_remove.ipynb
RecDP/examples/notebooks/llmutils/rag_text_fix.ipynb
RecDP/examples/notebooks/llmutils/spelling_correction.ipynb
RecDP/examples/notebooks/llmutils/url_loader.ipynb
RecDP/pyrecdp/LLM/README.md

.
Add notebooks for new ops
For users to understand recdp capabilities
No need to test

[v1.2][ISSUE-306]Add notebooks for new ops

---

RecDP/examples/notebooks/llmutils/rag_cnvrg_pipeline.ipynb
RecDP/examples/notebooks/llmutils/rag_cnvrg_pipeline_step_by_step.ipynb
RecDP/pyrecdp/core/import_utils.py
RecDP/pyrecdp/primitives/llmutils/rag_data_extractor.py
RecDP/pyrecdp/primitives/operations/__init__.py
RecDP/pyrecdp/primitives/operations/constant/__init__.py
RecDP/pyrecdp/primitives/operations/doc_loader.py
RecDP/tests/test_llmutils_operations.py
RecDP/tests/test_llmutils_pipelines.py

Unify the implementation of UrlLoader. 
UT

[v 1.2] [ISSUE 493] Unify the implementation of UrlLoader. 

---

RecDP/Dockerfile/DockerfileUbuntu
RecDP/tests/test_llmutils_operations.py
RecDP/tests/test_llmutils_pipelines.py

update check_install for multiple nodes
local multi node test

[v1.2][ISSUE-488]update check_install for multiple nodes

---

.github/workflows/e2eaiok_recdp_release_pypi.yml
RecDP/setup.py

release with prefix

---

RecDP/pyrecdp/datasets/__init__.py
RecDP/pyrecdp/primitives/operations/text_ingestion.py
RecDP/pyrecdp/primitives/operations/text_reader.py

…compute embedding, and no need to set up resources
Embedding performance improvement: Use function instead of caller to compute embedding, and no need to set up resources

[ISSUE-511] Embedding performance improvement: Use function instead of caller to compute embedding, and no need to set up resources

---

RecDP/pyrecdp/primitives/operations/text_ingestion.py

A after CI/CD bug is detected, trace back to PR-514, need to fix firstly to pass reamining PRs
Bug Fixing
existing Unittests

[v1.3][ISSUE-511]Update text_ingestion.py

---

RecDP/pyrecdp/primitives/llmutils/rag_data_extractor.py
RecDP/setup.py

Refine rag_data_extractor offline script.
UT

[v1.2][ISSUE-306]Refine rag_data_extractor offline script.

---

README.md

I fixed a grammar issue in the README.
Intel customers can read without grammatical issues.
N/A

Fixed capitalization error in README.md
